[features]
seeds = false
skip-lint = false
[programs.localnet]
pixel_game = "3UukPvWro2LyhZWX7rLEkKD6U8jTH1AUeq6w18FKUe8W"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/raidr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
