[features]
seeds = false
skip-lint = false
[programs.devnet]
pixel_game = "FEkTfdHNSnhGpqSUePtm5FesUUJzhbJ7jhFCUWhEMPCc"
nft_stake_vault = "4g1CcTvcuwpLZZucwYXeAHVtu8HmQkaT4tkkPVU1bemK"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/raidr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
